export const PHYSICS_CONSTANTS = {
  FRAME_SKIP: 2,
  REPULSION_FORCE: 500,
  REPULSION_DISTANCE: 200,
  SPRING_STRENGTH: 0.03,
  LINK_DISTANCE: 150,
  CENTER_ATTRACTION: 0.001,
  CENTER_ATTRACTION_THRESHOLD: 300,
  VELOCITY_DAMPING: 0.8,
  MIN_VELOCITY_THRESHOLD: 0.01,
  BOUNDARY_MARGIN: 50,
  // Physics simulation control
  STABILITY_THRESHOLD: 0.5,
  STABLE_FRAMES_NEEDED: 60,
} as const;

export const LAYOUT_CONSTANTS = {
  INITIAL_RADIUS_MIN: 150,
  INITIAL_RADIUS_BASE: 50,
  INITIAL_RADIUS_MULTIPLIER: 10,
  INITIAL_RADIUS_RANDOM: 50,
  INITIAL_ANGLE_RANDOM: 0.5,
  RESET_RADIUS_MIN: 300,
  RESET_RADIUS_BASE: 100,
  RESET_RADIUS_MULTIPLIER: 15,
} as const;

export const NODE_CONSTANTS = {
  DEFAULT_RADIUS: 36,
  SELECTED_RADIUS: 42,
  STROKE_WIDTH_DEFAULT: 2,
  STROKE_WIDTH_SELECTED: 3,
  EDGE_OFFSET: 25,
  LABEL_OFFSET_Y: -8, // Changed to keep label inside circle
  NAME_OFFSET_Y: 8,   // Changed to keep name inside circle
  MAX_NAME_LENGTH: 12,
} as const;

export const UI_CONSTANTS = {
  TOOLBAR_SPACING: 16,
  TOOLBAR_GAP: 8,
  BUTTON_PADDING: 8,
  BUTTON_PADDING_EXTENDED: 12,
  BORDER_RADIUS: 4,
  ICON_SIZE: 16,
  FONT_SIZE_SMALL: 7,
  FONT_SIZE_MEDIUM: 12,
  FONT_SIZE_DEFAULT: 14,
  ZOOM_STEP: 0.2,
  ZOOM_MIN: 0.3,
  ZOOM_MAX: 3,
  OPACITY_HOVER: 0.8,
  OPACITY_DEFAULT: 1,
} as const;

export const COLORS = {
  BACKGROUND: "#1f2937",
  BUTTON_BG: "#374151",
  BUTTON_HOVER: "#4B5563",
  TEXT_WHITE: "white",
  TEXT_GRAY: "#d1d5db",
  STROKE_DEFAULT: "#2C3E50",
  STROKE_SELECTED: "#FFD700",
  ARROW_FILL: "#666",
  DEFAULT_NODE_COLOR: "#95A5A6",
  DEFAULT_EDGE_COLOR: "#666",
} as const;

export const MARKER_CONSTANTS = {
  WIDTH: 10,
  HEIGHT: 7,
  REF_X: 9,
  REF_Y: 3.5,
} as const;

export const TIMING_CONSTANTS = {
  PHYSICS_STABILIZATION_TIMEOUT: 3000,
  DRAG_RELEASE_TIMEOUT: 1000,
  RESET_PHYSICS_TIMEOUT: 2000,
} as const;